apiVersion: v1
kind: Pod
metadata:
  name: imms
  namespace: default
  annotations:
    container.apparmor.security.beta.kubernetes.io/imms: unconfined

spec:
  containers:
  - image: localhost:32000/imms:1.2.1
    env:
    - name: IMMS_ORG
      value: example.com
    #- name: IMMS_CERT_COUNTRY
    #  value: '["JP"]'
    #- name: IMMS_CERT_LOCALITY
    #  value: '["Tokyo"]'
    #- name: IMMS_CERT_PROVINCE
    #  value: '["Shinagawa"]'
    ## - name: IMMS_EXTERNAL_IP
    ##   value: ""
    ## - name: IMMS_REGISTRY
    ##   value: ""
    #- name: IMMS_DOCKER_IO_CRED
    #  value: username:password
      
    #command:
    #  - sleep
    #  - "365d"
    imagePullPolicy: IfNotPresent
    name: imms
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"] # To pull docker images, a program needs the overlay2 mount.
    volumeMounts:
    - mountPath: /var/lib/ImmutableST/org
      name: work-vol
    - mountPath: /work
      name: temp-image-store
  restartPolicy: Never
  volumes:
  - name: work-vol
    hostPath:
      path: /var/lib/ImmutableST/org
      type: DirectoryOrCreate
  - name: temp-image-store
    emptyDir: {}
  dnsConfig:
    options:
    - name: ndots
      value: "1"
