apiVersion: v1
kind: Pod
metadata:
  name: imms
  namespace: default
spec:
  containers:
  - image: localhost:32000/imms:1.2.0
    env:
    - name: IMMS_ORG
      value: example.com
    #- name: IMMS_CERT_COUNTRY
    #  value: '["JP"]'
    #- name: IMMS_CERT_LOCALITY
    #  value: '["Tokyo"]'
    #- name: IMMS_CERT_PROVINCE
    #  value: '["Shinagawa"]'
    ## - name: IMMS_EXTERNAL_IP
    ##   value: ""
    ## - name: IMMS_REGISTRY
    ##   value: ""
    #- name: IMMS_DOCKER_IO_CRED
    #  value: username:password
      
    #command:
    #  - sleep
    #  - "365d"
    imagePullPolicy: IfNotPresent
    name: imms
    volumeMounts:
    - mountPath: /var/lib/ImmutableST/org
      name: work-vol
    - mountPath: /run/containerd.sock
      name: containerd-sock
  restartPolicy: Never
  volumes:
  - name: work-vol
    hostPath:
      path: /var/lib/ImmutableST/org
      type: DirectoryOrCreate
  - name: containerd-sock
    hostPath:
      path: /var/snap/microk8s/common/run/containerd.sock
      type: Socket
  dnsConfig:
    options:
    - name: ndots
      value: "1"
