// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: libimmds.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_libimmds_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_libimmds_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_libimmds_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_libimmds_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_libimmds_2eproto;
namespace libimmds {
class TxIdList;
class TxIdListDefaultTypeInternal;
extern TxIdListDefaultTypeInternal _TxIdList_default_instance_;
}  // namespace libimmds
PROTOBUF_NAMESPACE_OPEN
template<> ::libimmds::TxIdList* Arena::CreateMaybeMessage<::libimmds::TxIdList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace libimmds {

// ===================================================================

class TxIdList PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:libimmds.TxIdList) */ {
 public:
  inline TxIdList() : TxIdList(nullptr) {};
  virtual ~TxIdList();

  TxIdList(const TxIdList& from);
  TxIdList(TxIdList&& from) noexcept
    : TxIdList() {
    *this = ::std::move(from);
  }

  inline TxIdList& operator=(const TxIdList& from) {
    CopyFrom(from);
    return *this;
  }
  inline TxIdList& operator=(TxIdList&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TxIdList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TxIdList* internal_default_instance() {
    return reinterpret_cast<const TxIdList*>(
               &_TxIdList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TxIdList& a, TxIdList& b) {
    a.Swap(&b);
  }
  inline void Swap(TxIdList* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TxIdList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TxIdList* New() const final {
    return CreateMaybeMessage<TxIdList>(nullptr);
  }

  TxIdList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TxIdList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TxIdList& from);
  void MergeFrom(const TxIdList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TxIdList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "libimmds.TxIdList";
  }
  protected:
  explicit TxIdList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_libimmds_2eproto);
    return ::descriptor_table_libimmds_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTxIDFieldNumber = 1,
  };
  // repeated string TxID = 1;
  int txid_size() const;
  private:
  int _internal_txid_size() const;
  public:
  void clear_txid();
  const std::string& txid(int index) const;
  std::string* mutable_txid(int index);
  void set_txid(int index, const std::string& value);
  void set_txid(int index, std::string&& value);
  void set_txid(int index, const char* value);
  void set_txid(int index, const char* value, size_t size);
  std::string* add_txid();
  void add_txid(const std::string& value);
  void add_txid(std::string&& value);
  void add_txid(const char* value);
  void add_txid(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& txid() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_txid();
  private:
  const std::string& _internal_txid(int index) const;
  std::string* _internal_add_txid();
  public:

  // @@protoc_insertion_point(class_scope:libimmds.TxIdList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> txid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_libimmds_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TxIdList

// repeated string TxID = 1;
inline int TxIdList::_internal_txid_size() const {
  return txid_.size();
}
inline int TxIdList::txid_size() const {
  return _internal_txid_size();
}
inline void TxIdList::clear_txid() {
  txid_.Clear();
}
inline std::string* TxIdList::add_txid() {
  // @@protoc_insertion_point(field_add_mutable:libimmds.TxIdList.TxID)
  return _internal_add_txid();
}
inline const std::string& TxIdList::_internal_txid(int index) const {
  return txid_.Get(index);
}
inline const std::string& TxIdList::txid(int index) const {
  // @@protoc_insertion_point(field_get:libimmds.TxIdList.TxID)
  return _internal_txid(index);
}
inline std::string* TxIdList::mutable_txid(int index) {
  // @@protoc_insertion_point(field_mutable:libimmds.TxIdList.TxID)
  return txid_.Mutable(index);
}
inline void TxIdList::set_txid(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:libimmds.TxIdList.TxID)
  txid_.Mutable(index)->assign(value);
}
inline void TxIdList::set_txid(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:libimmds.TxIdList.TxID)
  txid_.Mutable(index)->assign(std::move(value));
}
inline void TxIdList::set_txid(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  txid_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:libimmds.TxIdList.TxID)
}
inline void TxIdList::set_txid(int index, const char* value, size_t size) {
  txid_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:libimmds.TxIdList.TxID)
}
inline std::string* TxIdList::_internal_add_txid() {
  return txid_.Add();
}
inline void TxIdList::add_txid(const std::string& value) {
  txid_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:libimmds.TxIdList.TxID)
}
inline void TxIdList::add_txid(std::string&& value) {
  txid_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:libimmds.TxIdList.TxID)
}
inline void TxIdList::add_txid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  txid_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:libimmds.TxIdList.TxID)
}
inline void TxIdList::add_txid(const char* value, size_t size) {
  txid_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:libimmds.TxIdList.TxID)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TxIdList::txid() const {
  // @@protoc_insertion_point(field_list:libimmds.TxIdList.TxID)
  return txid_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TxIdList::mutable_txid() {
  // @@protoc_insertion_point(field_mutable_list:libimmds.TxIdList.TxID)
  return &txid_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace libimmds

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_libimmds_2eproto
