name: imm-client
base: core20
version: 1.1.0
summary: Examples for Immutable Storage client, and a tool for the rsyslog
description: |
  imm-client.cc, imm-client,c and imm-client.go are examples for C++, C and golang, respectively.

type: app
grade: devel
confinement: devmode
apps:
  cc:
    command: bin/cc_immds
  c:
    command: bin/c_immds
  go:
    command: bin/go_immst
  rsyslog2imm:
    command: bin/rsyslog2imm
    
parts:
  c:
    plugin: nil
    after:
      - cc
  cc:
    plugin: make
    source: .
    source-subdir: app/example
    source-type: local
    build-packages: [gcc,g++]
    override-build: |
      (cd /root/stage; /usr/bin/find -print | cpio -o | cpio -idu -D /)
      snapcraftctl build
    after:
      - libimmds
  go:
    plugin: go
    source: .
    source-subdir: app/example-go
    source-type: local
  rsyslog2imm:
    plugin: go
    source: .
    source-subdir: app/rsyslog2imm
    source-type: local
  libimmds:
    plugin: make
    source: .
    source-subdir: libimmds
    source-type: local
    override-build: |
      (cd /root/stage; /usr/bin/find -print | cpio -o | cpio -idu -D /)
      snapcraftctl build
    organize:
      lib/libimmds.so: usr/lib/libimmds.so
    after:
      - libprotobuf
    
  libprotobuf:
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr --disable-static
    build-packages:
      - unzip
      - curl
    stage-packages: []
    source: https://github.com/protocolbuffers/protobuf.git
    source-type: git
    source-tag: v3.12.4
